version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.6.0
    command: ganache -d
    ports:
      - "9999:8545"

  deployer:
    build: .
    command: "sh -c '
      apk add jq;
      SADDLE_BUILD=/build npx saddle compile;
      GAS=6721975 SADDLE_BUILD=/build npx saddle deploy OpenOraclePriceData;
      GAS=6721975 SADDLE_BUILD=/build npx saddle deploy DelFiPrice $$(cat /build/development.json | jq -r .OpenOraclePriceData) 0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1,0xffcf8fdee72ac11b5c542428b35eef5769c409f0
    '"
    environment:
      - PROVIDER=http://ganache:8545
    depends_on:
      - ganache
    volumes:
      - ./.dockerbuild:/build

  reporter-1:
    build: sdk/javascript
    command: npm run start --
      --private_key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
      --script examples/fixed.js
    ports:
      - "3001:3000"

  reporter-2:
    build: sdk/javascript
    command: npm run start --
      --private_key 0x6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1
      --script examples/fixed.js
    ports:
      - "3002:3000"

  poster:
    build: poster
    command: "sh -c '
      apk add jq;
      while [ ! -f /build/development.json ]; do echo waiting for /build/development.json; sleep 1; done;
      npm run start --
      --poster_key 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
      --sources http://reporter-1:3000/prices.json,http://reporter-2:3000/prices.json
      --view_address $$(cat /build/development.json | jq -r .DelFiPrice)
      --web3_provider http://ganache:8545
    '"
    depends_on:
      - deployer 
      - reporter-1
      - reporter-2
    restart: "always"
    volumes:
      - ./.dockerbuild:/build
